version: '3.8'

services:
  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker

  api:
    container_name: api-container
    image: node:20
    working_dir: /usr/app/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run start"
    volumes:
      - ./dist/:/usr/app/clean-node-api/dist/
      - ./package.json:/usr/app/clean-node-api/package.json
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongo
