version: '3.8'

services:
  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker

  api:
    container_name: api-container
    build: .
    image: clean-node-api
    command: npm start
    volumes:
      - ./dist:/usr/app/clean-node-api/dist
    ports:
      - 5050:5050
    links:
      - mongo
